force-app/main/default/objects/Product2/fields/Additional__c.field-meta.xml
<CustomField>
    <fullName>Additional__c</fullName>
    <label>Additional</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Conference_Room</fullName>
                <label>Conference Room</label>
            </value>
            <value>
                <fullName>Callboxes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <description>Usable Area of Busines Premises</description>
    <label>Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bathroom__c.field-meta.xml
<CustomField>
    <fullName>Bathroom__c</fullName>
    <inlineHelpText>Select all equipment</inlineHelpText>
    <label>Bathroom</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bath</fullName>
            </value>
            <value>
                <fullName>Shower</fullName>
            </value>
            <value>
                <fullName>Hydro Massage</fullName>
            </value>
            <value>
                <fullName>Sauna</fullName>
            </value>
            <value>
                <fullName>Jacuzzi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Facilities_For_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Facilities_For_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Does this premise contains any facilities for disabled people to help them access and/or use it?</inlineHelpText>
    <label>Facilities For Disabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Furnished__c.field-meta.xml
<CustomField>
    <fullName>Furnished__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the Apartment furnished?</description>
    <inlineHelpText>Is the Apartment furnished?</inlineHelpText>
    <label>Furnished</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Garage_space__c.field-meta.xml
<CustomField>
    <fullName>Garage_space__c</fullName>
    <inlineHelpText>How many square meters does garage have?</inlineHelpText>
    <label>Garage_space</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Kitchen__c.field-meta.xml
<CustomField>
    <fullName>Kitchen__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is there a kitchen or kitchenette</description>
    <inlineHelpText>Is there a kitchen or kitchenette?</inlineHelpText>
    <label>Kitchen</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Parking_spaces__c.field-meta.xml
<CustomField>
    <fullName>Parking_spaces__c</fullName>
    <label>Parking spaces</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Rooms__c.field-meta.xml
<CustomField>
    <fullName>Rooms__c</fullName>
    <inlineHelpText>How many rooms does this apartment have?</inlineHelpText>
    <label>Rooms</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Swimming_Pool__c.field-meta.xml
<CustomField>
    <fullName>Swimming_Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is there an access to a swimming pool?</inlineHelpText>
    <label>Swimming Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Toilet__c.field-meta.xml
<CustomField>
    <fullName>Toilet__c</fullName>
    <label>Toilet</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Internal toilet</fullName>
                <default>true</default>
                <label>Internal toilet</label>
            </value>
            <value>
                <fullName>Shared toilet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Apartments.recordType-meta.xml
<RecordType>
    <fullName>Apartments</fullName>
    <active>true</active>
    <label>Apartments</label>
</RecordType>

force-app/main/default/classes/RE_SearchEngineController.cls
public with sharing class RE_SearchEngineController {
    
    public class PropertyWrapper
    {
        @AuraEnabled
        public String name{get;set;}
        @AuraEnabled
        public Decimal areaMin{get;set;}
        @AuraEnabled
        public Decimal areaMax{get;set;}
        @AuraEnabled
        public Boolean isKitchen{get;set;}
        @AuraEnabled
        public Boolean isSwimming{get;set;}
        @AuraEnabled
        public Boolean isFacilities{get;set;}
        @AuraEnabled
        public Boolean isFurnished{get;set;}
        @AuraEnabled
        public String location{get;set;}
        @AuraEnabled
        public String toilet{get;set;}
        @AuraEnabled
        public Integer noRooms{get;set;}
        @AuraEnabled
        public Integer garageSpaces{get;set;}
        @AuraEnabled
        public Integer parkingSpaces{get;set;}
        @AuraEnabled
        public List<String> additional{get;set;}
        @AuraEnabled
        public List<String> bathroom{get;set;}
        @AuraEnabled
        public Integer limitV{get;set;}
        @AuraEnabled
        public Integer offsetV { get; set; }
    }

    @AuraEnabled(Cacheable = true)
    public static list<Product2> getPropertiesData(PropertyWrapper wrapper, String recordType){
        try{
            system.debug(wrapper);

            String query = queryBuilder(wrapper,recordType);
           
            system.debug(query);

                List<Product2> prodLst = Database.query(query);
                for(Product2 p:prodLst){
                    if(p.DisplayUrl==null){
                        p.DisplayUrl = '/resource/1669234517000/RE_NoImage';
                    }
                }

            if(prodLst.isEmpty()) {
                throw new AuraHandledException('No Record Found..');
            }
            return prodLst; 
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(Cacheable = true)
    public static String getProductsCount(String recordType) {
        try{
            List<Product2> products = [SELECT Id, Name, RecordType.Name FROM Product2 WHERE RecordType.Name LIKE: recordType];
            Integer count = products.size();
            List<String> labelValues = new List<String>();
            labelValues.add(String.valueOf(count));
            String label = Label.RE_FindPropTitle;
            String title = String.format(label, labelValues);    
            return title;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }


    @AuraEnabled(cacheable = true)
    public static AggregateResult[] getProductPrice(String productId) {
        try{
            AggregateResult[] groupedResults = [SELECT MIN(UnitPrice) FROM PricebookEntry WHERE Product2Id =: productId AND Pricebook2.isActive = true];
            return groupedResults;  
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable = true)
    public static PricebookEntry getStandardProductPrice(String productId) {
        try{
            PricebookEntry standardPrice = [SELECT UnitPrice FROM PricebookEntry WHERE Pricebook2.isStandard = true AND Product2Id =: productId LIMIT 1];
            return standardPrice;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(Cacheable = true)
    public static String getCurrentUserRole() {
        try{    
            UserRole role = new UserRole();
            String uRoleId = UserInfo.getUserRoleId();
            if(uRoleId!=null){
                role = [SELECT Id, Name FROM UserRole WHERE Id =: uRoleId];
            }
                return role.Name;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }    

    private static String queryBuilder(PropertyWrapper wrapper, String recordType){
        try{
            wrapper.name = String.escapeSingleQuotes(wrapper.name);
            wrapper.name = '\'%' + wrapper.name + '%\'';
            String query='SELECT  Id, Name, Description, Street__c, Postal_Code__c, City__c, RecordType.Name, DisplayUrl FROM Product2 WHERE Name LIKE '+wrapper.name+' AND RecordType.Name LIKE \'%'+recordType+'%\'';

            if(wrapper.areaMin!=null&&String.valueOf(wrapper.areaMin).length()>0){
                query+=' AND Area__c >= '+ wrapper.areaMin;
            }
            if(wrapper.areaMax!=null&&String.valueOf(wrapper.areaMax).length()>0){
                query+=' AND Area__c <= '+ wrapper.areaMax;
            }
            if(recordType == 'B2B'){
                if(wrapper.isKitchen!=null&&wrapper.isKitchen==true){
                    query+=' AND Kitchen__c = '+ wrapper.isKitchen;
                }
                if(wrapper.toilet!=null&&wrapper.toilet.length()>0){
                    query+=' AND Toilet__c = '+ wrapper.toilet;
                }
                if(wrapper.isFacilities!=null&&wrapper.isFacilities==true){
                    query+=' AND Facilities_For_Disabled__c = '+ wrapper.isFacilities;
                }
                if(wrapper.parkingSpaces!=null&&String.valueOf(wrapper.parkingSpaces).length()>0){
                    query+=' AND Parking_spaces__c >= '+ wrapper.parkingSpaces;
                }
                if(!wrapper.additional.isEmpty()){
                    String params='';
                    for(String a: wrapper.additional){
                        params += a+';';
                    }
                    params = params.removeEnd(';');
                    query+=' AND Additional__c includes (\''+params+'\')';
                }

            }
            if(recordType == 'Apartments'){
                if(wrapper.isSwimming!=null&&wrapper.isSwimming==true){
                    query+=' AND Swimming_Pool__c = '+ wrapper.isSwimming;
                }
                if(!wrapper.bathroom.isEmpty()){
                    String params='';
                    for(String b: wrapper.bathroom){
                        params += b+';';
                    }
                    params = params.removeEnd(';');
                    query+=' AND Bathroom__c includes (\''+params+'\')';
                }
                if(wrapper.isFurnished!=null&&wrapper.isFurnished==true){
                    query+=' AND Furnished__c = '+ wrapper.isFurnished;
                }
                if(wrapper.garageSpaces!=null&&String.valueOf(wrapper.garageSpaces).length()>0){
                    query+=' AND Garage_space__c >= '+ wrapper.garageSpaces;
                }
                if(wrapper.noRooms!=null&&String.valueOf(wrapper.noRooms).length()>0){
                    query+=' AND Rooms__c >= '+ wrapper.noRooms;
                }

            }
            if(!String.isBlank(wrapper.location)){
                wrapper.location = String.escapeSingleQuotes(wrapper.location);
                wrapper.location = '\'%' + wrapper.location + '%\'';
                query+=' AND City__c LIKE '+wrapper.location;
            }
            query += ' LIMIT '+wrapper.limitV+' OFFSET '+wrapper.offsetV;

            system.debug(query);
            return query; 
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
        
    }
}