force-app/main/default/objects/Product2/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>24</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>8</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RE_SearchEngineControllerTest.cls
@isTest
private class RE_SearchEngineControllerTest{

	@testSetup static void setup(){

		Product2 product2Obj = new Product2 (
			Description = 'Test Value', 
			DisplayUrl = 'www.google.com', 
			Name = 'test value', 
			Street__c = 'test value', 
			City__c = 'test value', 
			Postal_Code__c = 'test value', 
			Country__c = 'test value'
		);
		insert product2Obj;
		 Pricebookentry pricebookentryObj = new Pricebookentry (
			UnitPrice = 1.1
		);
		insert pricebookentryObj;
		 Userrole userroleObj = new Userrole (
			Name = 'test value', 
			OpportunityAccessForAccountOwner ='None'
		);
		insert userroleObj;
		 
	}

	@isTest static void testMethod1() {
		// code_block	
	}

	@isTest static void testMethod2() {
		// code_block	
	}
}